# -*- coding: utf-8 -*-
"""codeexplain

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cg72m2pU5I8f1i3isrjhsB9pDStQ-qMZ
"""

!pip install transformers gradio --upgrade --no-cache-dir

from transformers import pipeline
import gradio as gr

# Load a code explanation model (text2text)
explain_model = pipeline("text2text-generation", model="SEBIS/code_trans_t5_small_code_documentation_generation_python_multitask_finetune")

# Function to explain code
def explain_code(code):
    if not code.strip():
        return "Please enter some code."

    prompt = f"Generate documentation for the following code:\n{code}"
    result = explain_model(prompt, max_length=200, do_sample=False)[0]['generated_text']
    return result

# Gradio UI
gr.Interface(
    fn=explain_code,
    inputs=gr.Textbox(lines=10, label="Paste your Code here (Python, C, etc.)"),
    outputs=gr.Textbox(label="📖 AI Explanation / Debug Hint"),
    title="🧑‍💻 Code Explain & Debug Bot",
    description="Paste your code and let the AI explain what it does. Great for learning and debugging!",
    theme="default"
).launch()