# -*- coding: utf-8 -*-
"""travel guide bot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BS4F59UqI7aFuxICkWoHEnCkXzdhKi8p
"""

import gradio as gr
import requests

# 🔐 API Keys
OPENWEATHER_API_KEY = "dc3645e5f1f4e32feec765f31d2c2aa4"
IQAIR_API_KEY = "a122358c-748c-4e18-93ef-bd845fb72fdf"

# 🎶 Spotify iframe map (all lowercase keys!)
city_songs = {
    "madurai": """<iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/01DI9ukDAOufyY0C6LnLAR?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>""",
    "chennai": """<iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/0CK97qVzUdaZJ2FpSQZLIS?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>""",
    "thoothukudi": """<iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/3c9ccP0KmY3j8OWc5mxrc4?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>""",
    "virudhunagar": """<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/3FiDc5ConilJ5UuS2YVfwp?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>""",
    "sivakasi": """<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/1FF03wgIwcQO9AVobnKpdb?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>""",
    "coimbatore": """<iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/4d0TVeIlWA4OCu3wnoTo73?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>"""
}

# 🌟 Fallback for other cities
fallback_playlist = """<iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/2TwT7sQlLowP4xyV524Xm2?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>"""

# 📚 Wikipedia Summary
def get_wikipedia_summary(city):
    url = f"https://en.wikipedia.org/api/rest_v1/page/summary/{city}"
    res = requests.get(url).json()
    return res.get("extract", "No info found on Wikipedia.")

# 🌦️ Weather + Time + Coordinates
def get_weather_and_time(city):
    url = "http://api.openweathermap.org/data/2.5/weather"
    params = {"q": city, "appid": OPENWEATHER_API_KEY, "units": "metric"}
    res = requests.get(url, params=params).json()

    if res.get("cod") != 200:
        return "Weather info not found.", "Time info not available.", None, None

    desc = res["weather"][0]["description"].capitalize()
    temp = res["main"]["temp"]
    humidity = res["main"]["humidity"]
    weather_info = f"{desc} | 🌡️ {temp}°C | 💧 Humidity: {humidity}%"

    lat = res["coord"]["lat"]
    lon = res["coord"]["lon"]

    time_url = f"https://timeapi.io/api/Time/current/coordinate?latitude={lat}&longitude={lon}"
    time_res = requests.get(time_url).json()
    time = time_res.get("dateTime", "Time not available.")

    return weather_info, f"Local Time: {time}", lat, lon

# 🌫️ Air Quality Index
def get_air_quality(city, state="Tamil Nadu", country="India"):
    try:
        url = f"http://api.airvisual.com/v2/city?city={city}&state={state}&country={country}&key={IQAIR_API_KEY}"
        res = requests.get(url).json()
        if res.get("status") != "success":
            return "Air Quality info not available."
        aqi = res["data"]["current"]["pollution"]["aqius"]
        return f"🌫️ Air Quality Index (US AQI): {aqi}"
    except:
        return "Air Quality info error."

# 🗺️ Google Map Embed
def get_google_map_embed(city):
    city = city.replace(" ", "+")
    return f'<iframe width="100%" height="300" src="https://www.google.com/maps?q={city}&output=embed"></iframe>'

# 🎶 Spotify Embed (normalize to lowercase)
def get_spotify_embed(city):
    return city_songs.get(city.lower(), fallback_playlist)

# 🧠 Main Travel Bot Logic
def travel_bot(city):
    city_clean = city.strip().title()

    summary = get_wikipedia_summary(city_clean)
    weather, time, lat, lon = get_weather_and_time(city_clean)
    aqi = get_air_quality(city_clean)
    map_html = get_google_map_embed(city_clean)
    spotify_html = get_spotify_embed(city)

    markdown_output = f"""
## ✈️ Travel Guide for {city_clean}

**📚 About the City:**
{summary}

**🌦️ Weather Info:**
{weather}

**🕒 Local Time:**
{time}

**🌫️ Air Quality:**
{aqi}

**🎶 Music Vibe:**
Enjoy a Tamil song while you explore {city_clean}!
"""

    return markdown_output, map_html, spotify_html

# 🚀 Gradio UI
gr.Interface(
    fn=travel_bot,
    inputs=gr.Textbox(label="Enter a Tamil Nadu City"),
    outputs=[
        gr.Markdown(label="🧭 Travel Info"),
        gr.HTML(label="🗺️ City Map"),
        gr.HTML(label="🎧 Spotify Vibe")
    ],
    title="🎧 Travel Companion",
    description="Enter a Tamil Nadu city name to get weather, map, Wikipedia summary, air quality, and a hand-picked Tamil song."
).launch()